#TensorFlow Developer Certificate

## Introduction to TensorFlow (CHAPTER 2)

 ## Data Representation 

Reference 1 for Tensors: https://www.tensorflow.org/api_docs/python/tf/Tensor

Reference 2 for errors: https://www.tensorflow.org/api_docs/python/tf/errors

Reference 3 for Hello World: https://www.tensorflow.org/tutorials/keras/regression

https://www.youtube.com/watch?v=-vHQub0NXI4&list=RDCMUC0rqucBdTuFTjJiefW5t-IQ&start_radio=1

The goal of this notebook is to understand data represenation with TensorFlow

In [51]:
#pip install Tensorflow

In [52]:
#Import required libraries
import tensorflow as tf
import numpy as np
from numpy import *

In [53]:
print(tf.__version__)

2.8.0


#Creating tensors using 
* tf.constant()
* tf.variables()
* tf.range()

In [54]:
#Creating a tensor object using tf constant
a_constant = tf.constant([1, 2, 3, 4 ,5,6])
a_constant

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [55]:
#Creating a tensor object using tf constant 
a_variable = tf.Variable([1, 2, 3, 4 ,5,6])
a_variable

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [56]:
# Creating tensors using the range function 
a_range = tf.range(start=1, limit=7)
a_range

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

#Tensor Rank

In [57]:
#scalar
a = tf.constant(1)
a

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [58]:
#vector 
b= tf.constant([1.2,2.3,3.4,4.5])
b

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.2, 2.3, 3.4, 4.5], dtype=float32)>

In [59]:
#matrix
c =tf.constant([[1,2],[3,4]])
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [60]:
#3-dimensional tensor
d=tf.constant([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
d

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]], dtype=int32)>

# Properties of tensors

In [61]:
#scalar
a = tf.Variable(1.1, name="TDC", dtype=float16)
a

<tf.Variable 'TDC:0' shape=() dtype=float16, numpy=1.1>

In [62]:
#vector 
b= tf.Variable([1.2,2.3,3.4,4.5], name="'Vector",dtype=float64)
b

<tf.Variable ''Vector:0' shape=(4,) dtype=float64, numpy=array([1.2, 2.3, 3.4, 4.5])>

### Rank of a tensor

In [63]:
#scalar
a = tf.constant(1.1)
#vector
b= tf.constant([1.2,2.3,3.4,4.5])
#matrix
c =tf.constant([[1,2],[3,4]])
#Generating tensor rank
print("The rank of the scalar is: ",tf.rank(a))
print(" ")
print("The rank of the vector is: ",tf.rank(b))
print(" ")
print("The rank of the matrix is: ",tf.rank(c))


The rank of the scalar is:  tf.Tensor(0, shape=(), dtype=int32)
 
The rank of the vector is:  tf.Tensor(1, shape=(), dtype=int32)
 
The rank of the matrix is:  tf.Tensor(2, shape=(), dtype=int32)


In [64]:
#Generating details of the dimension

print("The dimension of the scalar is: ",a.ndim)
print(" ")
print("The dimension of the vector is: ",b.ndim)
print(" ")
print("The dimension of the matrix is: ",c.ndim)


The dimension of the scalar is:  0
 
The dimension of the vector is:  1
 
The dimension of the matrix is:  2


### Datatype of a tensor

In [65]:
#printing the data type 
print("The data type of the scalar is: ",a.dtype)
print(" ")
print("The data type of the vector is: ",b.dtype)
print(" ")
print("The data type of the matrix is: ",c.dtype)


The data type of the scalar is:  <dtype: 'float32'>
 
The data type of the vector is:  <dtype: 'float32'>
 
The data type of the matrix is:  <dtype: 'int32'>


### Shape of tensors

In [66]:
#Generating details of the tensor shape
print("The Shape of the scalar is: ",a.shape)
print(" ")
print("The Shape of the vector is: ",b.shape)
print(" ")
print("The Shape of the matrix is: ",c.shape)


The Shape of the scalar is:  ()
 
The Shape of the vector is:  (4,)
 
The Shape of the matrix is:  (2, 2)


In [67]:
#Generating number of elements in a tensor 
print("The Size of the scalar is: ",tf.size(a))
print(" ")
print("The Size of the vector is: ",tf.size(b))
print(" ")
print("The Size of the matrix is: ",tf.size(c))


The Size of the scalar is:  tf.Tensor(1, shape=(), dtype=int32)
 
The Size of the vector is:  tf.Tensor(4, shape=(), dtype=int32)
 
The Size of the matrix is:  tf.Tensor(4, shape=(), dtype=int32)


#Basic tensor operations

### Changing Data type

In [68]:
a=tf.constant([1,2,3,4,5])
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [69]:
#changing the datatype from int32 to float 32
a =tf.cast(a,dtype=float32)
a

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

### Indexing 

In [70]:
# Create a 2 x2 matrix 
a = tf.constant([[1, 2],[3, 4]], dtype=float32)
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [71]:
# Indexing using method 1
a[0]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [72]:
# Indexing 
a[0][1]

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [73]:
#Method 2
c = tf.constant([0, 1, 2, 3, 4, 5])
print(tf.slice(c,begin=[2],size=[4]))


tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


### Expanding a matrix

In [74]:
tf.expand_dims(a,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.]]], dtype=float32)>

In [75]:
(tf.expand_dims(a,axis=0)).shape,(tf.expand_dims(a,axis=1)).shape,(tf.expand_dims(a,axis=-1)).shape

(TensorShape([1, 2, 2]), TensorShape([2, 1, 2]), TensorShape([2, 2, 1]))

### Tensor Aggregation

In [76]:
import random
a = random.sample(range(1, 100), 50)
a = tf.constant(a)

In [77]:
a

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([63, 65, 17, 30, 84, 96, 87, 39, 92, 29, 61,  7, 86, 35, 32, 62, 81,
       97,  2, 50, 82, 53,  9, 70, 40, 38, 34, 13, 68, 59, 21, 64, 89,  8,
       79, 22, 94, 88, 85, 43, 15, 54, 73, 27, 60, 77, 75, 45, 25, 16],
      dtype=int32)>

In [78]:
print("The smallest number in our vector is : ",tf.reduce_min(a))
print(" ")
print("The largest number in our vector is: ",tf.reduce_max(a))
print(" ")
print("The sum of our vector is : ",tf.reduce_sum(a))
print(" ")
print("The mean of our vector is: ",tf.reduce_mean(a))

The smallest number in our vector is :  tf.Tensor(2, shape=(), dtype=int32)
 
The largest number in our vector is:  tf.Tensor(97, shape=(), dtype=int32)
 
The sum of our vector is :  tf.Tensor(2641, shape=(), dtype=int32)
 
The mean of our vector is:  tf.Tensor(52, shape=(), dtype=int32)


In [79]:
print("The position that holds the lowest value is : ",tf.argmin(a))
print(" ")
print("The position that holds the highest value is: ",tf.argmax(a))

The position that holds the lowest value is :  tf.Tensor(18, shape=(), dtype=int64)
 
The position that holds the highest value is:  tf.Tensor(17, shape=(), dtype=int64)


In [80]:
a[tf.argmin(a)], a[tf.argmax(a)]

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=97>)

### Transpose and Reshape 

In [81]:
# Create a 3 x 4 matrix 
a = tf.constant([[1, 2,3,4],[5,6,7,8], [9,10,11,12]])
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)>

In [82]:
tf.reshape(a, shape=(2, 2,3))

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [83]:
tf.transpose(a)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]], dtype=int32)>

### Element wise operations 

In [84]:
a= tf.constant([1,2,3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [85]:
#Addition operation
print(a+4)
print(" ")
#Subtraction operation
print(a-4)
print(" ")
#Multiplication Operation
print(a*4)
print(" ")
#Division Operation
print(a/4)
print(" ")

tf.Tensor([5 6 7], shape=(3,), dtype=int32)
 
tf.Tensor([-3 -2 -1], shape=(3,), dtype=int32)
 
tf.Tensor([ 4  8 12], shape=(3,), dtype=int32)
 
tf.Tensor([0.25 0.5  0.75], shape=(3,), dtype=float64)
 


### Matrix multiplication

In [86]:
# 3 X 2 MATRIX
a = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

#2 X 3 MATRIX
b = tf.constant([[7,8,9],
                 [10,11,12]])

In [87]:
#matrix muplitication
tf.matmul(a,b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [88]:
#Mutiplying a with its transpose
tf.matmul(a,tf.transpose(a))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [89]:
#Mutiplying a with reshaped a. Hope you tried it out yourself?
tf.matmul(a,tf.reshape(a, shape =(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>